version: "3.8"
services:
    neo4j:
        image: neo4j
        ports:
            - 7474:7474
            - 7687:7687
        environment:
            - NEO4J_AUTH=neo4j/password
        container_name: neo4j
    backend:
        build: ./
        ports:
            - 5000:5000
        volumes:
            - ./src:/usr/src/app/src
        depends_on:
            - neo4j